thread pool with blocking queue
oquechy/java-II pull request #2
Opened 2018-02-24 13:23 UTC by oquechy

2018-05-02 12:33 UTC, yurii-litvinov requested changes

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueue.java
> +    private final Object modifiedSync = new Object();
Можно было саму queue использовать для синхронизации. Это тот самый разделяемый ресурс, который защищает монитор, queue не показывается наружу, так что она вполне норм.

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueue.java
> +                modifiedSync.notifyAll();
Может, лучше notify? Всё равно забрать значение из очереди сможет только один поток, а больше ничего интересного с ней не сделать.

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/LightExecutionException.java
> +public class LightExecutionException extends Exception {
Тоже нужен комментарий

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/LightFuture.java
> +    <U> LightFuture<U> thenApply(Function<T, U> mapping) throws InterruptedException, LightExecutionException;
Можно ослабить ограничение, не обязательно принимать именно T

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/ThreadPoolImpl.java
> +        public <V> LightFuture<V> thenApply(@NotNull Function<T, V> mapping) {
Тоже можно было ослабить ограничение на T

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/test/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueueTest.java
> +    public void add() throws InterruptedException {
Имена тестов лучше более содержательные

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/test/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueueTest.java
> +    }
А что этот тест, собственно, проверяет? Сложно сделать очередь, которая его НЕ пройдёт :) Надо либо в названии, либо в комментарии отразить как-то смысл теста, а то в реальной жизни сокомандники его быстро удалят как ненужный.

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/test/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueueTest.java
> +        @NotNull Object sync = new Object();
Мне кажется, в данном случае это слепое следование хорошим практикам, что может быть само по себе опасно --- https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D0%B3%D0%BE-%D0%BA%D1%83%D0%BB%D1%8C%D1%82. taken тут тоже вполне подходит как объект, по которому можно выполнять синхронизацию.

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/test/java/ru/spbau/mit/oquechy/threadpool/LightFutureImplTest.java
> +    private int cnt;
Лучше не сокращать имена

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/test/java/ru/spbau/mit/oquechy/threadpool/LightFutureImplTest.java
> +            return cnt++;
Атомарный инкремент тут был бы более уместен, такой код работает раз в 10 (или 100) медленнее, чем AtomicInteger.incrementAndGet()

2018-05-02 12:33 UTC, yurii-litvinov commented on hw1/src/test/java/ru/spbau/mit/oquechy/threadpool/LightFutureImplTest.java
> +    @NotNull
Надо разделять пустыми строками объявления

2018-05-11 19:14 UTC, oquechy commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueue.java
> +                modifiedSync.notifyAll();
Почему-то он не работает без notifyAll

2018-05-11 19:17 UTC, oquechy commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueue.java
> +                modifiedSync.notifyAll();
Конкретно, тест threadsCount виснет

2018-05-12 06:25 UTC, oquechy commented on hw1/src/main/java/ru/spbau/mit/oquechy/threadpool/ConcurrentQueue.java
> +                modifiedSync.notifyAll();
Починила

2018-05-23 19:13 UTC, yurii-litvinov approved these changes
Всё ок, зачтена

2018-07-06 09:36 UTC, merged