ftp server and client
oquechy/java-II pull request #5
Opened 2018-04-16 19:08 UTC by oquechy

2018-05-02 18:19 UTC, yurii-litvinov requested changes

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/gradlew
> +#!/usr/bin/env sh
Сам gradle-wrapper не выложен

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/client/FTPClient.java
> +    @NotNull
Лучше разделять поля пустыми строками

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/server/FTPServer.java
> +        }
Так к этому делу неудобно будет GUI писать. Цикл слушания сокета должен быть в отдельном методе (или даже в отдельном потоке, который сам же сервер и создаёт), чтобы в пользовательском коде можно было просто создать сервер, сказать ему слушать и забыть о нём.

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/types/FileEntry.java
> +public class FileEntry {
Мне кажется, эта штука вообще не нужна

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/client/FTPClient.java
> +     * @return fetched file or empty {@link FileEntry} if the file
Неправда :)

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/types/FileInfo.java
> +public class FileInfo {
Нужны комментарии

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/types/FileInfo.java
> +    public boolean isDirectory;
Вообще, даже если это data-класс, то ему всё равно надо геттеры/сеттеры. Паблик полей же не бывает, особенно мутабельных

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/test/java/ru/spbau/mit/oquechy/ftp/server/FTPTest.java
> +    public void list() throws IOException {
Хочется более подробных имён тестов

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/server/FTPServer.java
> +    public static Process start() throws IOException {
Это, конечно, вариант в плане удобства запуска сервера из пользовательского кода, но целый отдельный процесс с целой java-машиной --- слишком, гм, расточительно.

2018-05-02 18:19 UTC, yurii-litvinov commented on hw3/src/test/java/ru/spbau/mit/oquechy/ftp/server/FTPTest.java
> +        FileUtils.cleanDirectory(new File(DST_DIR));
Тут все тесты падают, говоря, что нет такой папки

2018-05-03 06:17 UTC, oquechy commented on hw3/src/test/java/ru/spbau/mit/oquechy/ftp/server/FTPTest.java
> +        FileUtils.cleanDirectory(new File(DST_DIR));
Intellij IDEA почему-то ставит по умолчанию working directory для тестов ".idea/modules". (Кстати, почему это логично?) Чтобы тестировать я в настройках конфигурации поставила %MODULE_WORKING_DIR% в качестве working directory. Как можно было сделать по-другому, из кода? Не нашла переменной, кроме user.dir, относительно которой можно было бы указывать пути.

2018-05-03 06:48 UTC, oquechy commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/server/FTPServer.java
> +    public static Process start() throws IOException {
Для тестов, как это делаю я, наверное, да. Но ведь хочется уметь запускать сервер так, чтобы он продолжал работать независимо от вызвавшего его кода и даже после его завершения. 

Думаю, что хорошо писать тесты так, как мог бы быть написан пользовательский код. Чтобы пользователь, посмотрев в тесты, увидел use case для основного кода.

2018-05-03 06:51 UTC, oquechy commented on hw3/src/main/java/ru.spbau.mit.oquechy.ftp/server/FTPServer.java
> +    public static Process start() throws IOException {
PS Спасибо за проверку дз 😇

2018-05-10 06:39 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2018-05-10 16:59 UTC, merged